const assert = require('assert');
const fs = require('fs');
const path = require('path');
const root = __dirname;
const readJson = (rel) => JSON.parse(fs.readFileSync(path.join(root, rel), 'utf8'));
const compat = readJson('read-model-compatibility.fixture.json');
assert.equal(compat.schemaVersion, 'gameplay-state-ability-evidence-compatibility.v1');
assert.equal(compat.stateReadModel.schemaVersion, 'gameplay-state-machine-read-model.v1');
assert.equal(compat.abilityReadModel.schemaVersion, 'gameplay-ability-action-read-model.v1');
assert.match(compat.stateReadModel.sourceRef, /state-machine\.valid\.fixture\.json/);
assert.match(compat.abilityReadModel.sourceRef, /ability-action\.valid\.fixture\.json/);
assert.ok(compat.consumerRules.some((rule) => /display\/evidence data only/.test(rule)));
assert.doesNotMatch(JSON.stringify(compat), /execute_script|plugin_loader|dynamic_import|eval\(|commandBridge|trustedWrite/);
const invalid = readJson('invalid/read-model-compatibility.invalid.fixture.json');
assert.match(JSON.stringify(invalid), /execute_script/);
assert.match(JSON.stringify(invalid), /trustedWrite/);
const doc = fs.readFileSync(path.join(root, '../../docs/gameplay-state-ability-evidence-compatibility-v1.md'), 'utf8');
assert.match(doc, /Issue: #614/);
assert.match(doc, /gameplay-state-machine-read-model\.v1/);
assert.match(doc, /gameplay-ability-action-read-model\.v1/);
assert.match(doc, /read-only summaries/);
assert.match(doc, /does not authorize arbitrary JS\/Rust\/Python\/Lua\/WASM execution/);
assert.match(doc, /#1 remains the roadmap\/final-goal anchor/);
assert.match(doc, /#23 remains the\s+memory\/governance anchor/);
assert.doesNotMatch(doc, /script runtime is implemented|eval is allowed|plugin loader is supported|command bridge enabled|trusted browser write enabled/);
console.log('gameplay state ability evidence compatibility smoke passed');
